include $(TOPDIR)/rules.mk

PKG_RELEASE:=1
PKG_VERSION:=0.6.10
PKG_NAME:=grid0-relay
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/cmake.mk

CMAKE_BINARY_SUBDIR := build-openwrt

define Package/$(PKG_NAME)
	SECTION:=net
	CATEGORY:=Network
	SUBMENU:=GRID0
	DEPENDS:=+libstdcpp +libatomic +libpcap +libpthread
	TITLE:=GRID0 Relay client
endef

define Package/$(PKG_NAME)/description
  Nintendo Switch LAN play carried over a ZeroTier network. Command line only;
  this build is unverified on OpenWRT hardware.
endef

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP) ./$(PKG_NAME)/* $(PKG_BUILD_DIR)/
endef

define Package/$(PKG_NAME)/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/build-openwrt/src/grid0-relay $(1)/usr/bin
endef

define Package/$(PKG_NAME)/postinst
endef

define Package/$(PKG_NAME)/prerm
endef

$(eval $(call BuildPackage,$(PKG_NAME)))
